# ДЗ 3 
## 2.11.19


### Импортировать NumPy под именем np
### Напечатать версию и конфигурацию

In [1]:
import numpy as np

print(np.version.version)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

### Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
zr = np.zeros(10)
zr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Создать вектор размера 10, заполненный единицами

In [3]:
on = np.ones(10)
on

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Создать вектор размера 10, заполненный числом 2.

In [4]:
arr = np.ones(10)
arr = list(map(lambda x: x * 2.5, arr))
print(arr)

z = np.full(10, 2.5)
print(z)

[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


### Как получить документацию о функции numpy.add из командной строки?

In [5]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-5-e4a7e6a4f2e9>, line 1)

### Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Создать вектор со значениями от 10 до 49



In [7]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Развернуть вектор (первый становится последним)

In [8]:
arr = np.arange(10)
arr = arr[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


### Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Найти индексы ненулевых элементов в [1,2,0,0,4,0]


In [10]:
a = np.array([1,2,0,0,4,0])
с = 0
for i in a:
    if i != 0:
        print(с)
    с = с + 1


ind = np.nonzero([1,2,0,0,4,0])
print(ind)

0
1
4
(array([0, 1, 4], dtype=int32),)


### Создать массив 3x3x3 со случайными значениями


In [11]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.83143037 0.83403186 0.11129628]
  [0.77749807 0.24087113 0.35383206]
  [0.99259566 0.70601204 0.20213303]]

 [[0.82900156 0.23978844 0.01993851]
  [0.17081569 0.14293776 0.00778587]
  [0.62371357 0.42133888 0.53091561]]

 [[0.2031579  0.6994857  0.98598903]
  [0.63551893 0.42852625 0.62851757]
  [0.61140685 0.74603059 0.55803518]]]


### Создать массив 10x10 со случайными значениями, найти минимум и максимум


In [12]:
arr = np.random.random((10,10))
print(arr.max())
print(arr.min())

0.9819394504709765
0.014789790870615271


### Создать случайный вектор размера 30 и найти среднее значение всех элементов


In [13]:
arr = np.random.random(30)
print(arr.mean())

0.45797050576319936


### Создать матрицу с 0 внутри, и 1 на границах


In [14]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Выяснить результат следующих выражений
#### (	0 * np.nan
#### np.nan == np.nan
#### np.inf > np.nan
#### np.nan - np.nan)


In [15]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


### Создать 5x5 матрицу с 1,2,3,4 под диагональю


In [16]:
arr = np.diag(np.arange(1, 5), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Создать 8x8 матрицу и заполнить её в шахматном порядке


In [17]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [18]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


### Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [19]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
